site_name: CAU-AISL

theme:
  #name: 'rtd-dropdown'
  name: 'material'
  language: ko
  features:
    - navigation.instant




# 기존에 일일히 
# nav:
#   - Home: index.md
#   - intro: 
#     - '안녕' : 'hello.md'
#   - Study:
#     - Filght Dynamics:
#       - '2023.07.03.md'
#
#use_directory_urls: false
